name: "DEV Workflow"

on:
  push:
    branches:
      - "dev"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: "dev"
      aws-assume-role-arn: "arn:aws:iam::654654414177:role/github-actions-bwsolucoes-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "cloudcose-site-tfstate-dev"